#!/bin/bash

if [ ! -f /tmp/nosplit-tunnel ] ; then
	echo "#@VPNC_GENERATED@ mab vpn file" > /etc/resolv.conf
	echo "nameserver 127.0.0.1" >> /etc/resolv.conf
	echo "search denofslack.org sourcefire.com sfeng.sourcefire.com englab.sourcefire.com cm.sourcefire.com" >> /etc/resolv.conf
fi
