#!/bin/bash

get_local_dns()
{
	localns=$(grep nameserver /etc/resolv.conf.SAVE_VPN | head -1 | cut -d' ' -f2)
	if [[ -z "${localns}" || ${localns} == "127.0.0.1" ]] ; then
			localns=8.8.8.8
	fi
	localsearch=$(grep search /etc/resolv.conf.SAVE_VPN | head -1 | sed -e 's/search //g')
	if [ -z "${localsearch}" ] ; then
		localsearch=$(grep domain /etc/resolv.conf.SAVE_VPN | head -1 | sed -e 's/domain //g')
	fi
	echo "Local DNS is ${localns}"
	echo "Local search domains are ${localsearch}"

}


if [ ! -f /tmp/nosplit-tunnel ] ; then

	killall dnsmasq

	get_local_dns

	dnsmasq -a 127.0.0.1 -h -R -S ${localns} -S /sourcefire.com/10.1.1.6 -S /sourcefire.com/10.1.1.7

	echo "#@VPNC_GENERATED@ mab split tunnel vpn file" > /etc/resolv.conf
	echo "nameserver 127.0.0.1" >> /etc/resolv.conf
	echo "search ${localsearch} sourcefire.com sfeng.sourcefire.com englab.sourcefire.com cm.sourcefire.com" >> /etc/resolv.conf
fi
