#!/bin/bash

killall dnsmasq

if [ -f /etc/resolv.conf.SAVE_VPN ] ; then
	echo "Restoring /etc/resolv.conf.SAVE_VPN to /etc/resolv.conf"
	cp -vf /etc/resolv.conf.SAVE_VPN /etc/resolv.conf
fi

sshfs_mounts=$(mount | grep sourcefire.com | cut -d' ' -f3 | xargs )
if [ -n "${sshfs_mounts}" ] ; then
	PLATFORM=$(uname )
	echo "Unmounting ${sshfs_mounts}"
	if [ ${PLATFORM} == "Linux" ] ; then
		fusermount -zu ${sshfs_mounts}
	elif [ ${PLATFORM} == "Darwin" ] ; then
		umount -f ${sshfs_mounts}
	fi
fi