#!/bin/bash

killall dnsmasq

if [ -f /etc/resolv.conf.SAVE_VPN ] ; then
	echo "Restoring /etc/resolv.conf.SAVE_VPN to /etc/resolv.conf"
	cp -vf /etc/resolv.conf.SAVE_VPN /etc/resolv.conf
fi

sshfs_mounts=$(mount | grep sourcefire.com | cut -d' ' -f3 | xargs )
if [ -n "${sshfs_mounts}" ] ; then
	PLATFORM=$(uname )
	for mount in ${sshfs_mounts} ; do 
		echo "Unmounting ${mount}"
		if [ ${PLATFORM} == "Linux" ] ; then
			fusermount -zu ${mount}
		elif [ ${PLATFORM} == "Darwin" ] ; then
			umount -f ${mount}
		fi
	done
fi