#!/bin/bash

SFNETWORKS=(
	"10.1.0.0/255.255.0.0/16"
	"10.2.0.0/255.255.0.0/6"
	"10.4.0.0/255.255.0.0/16"
	"10.5.0.0/255.255.0.0/16"
	"10.6.0.0/255.255.0.0/16"
	"10.11.0.0/255.255.0.0/16"
	"172.25.0.0/255.255.0.0/16"
)

if [ ! -f /tmp/nosplit-tunnel ] ; then
	i=0
	for NETWORK in "${SFNETWORKS[@]}" ; do
		echo "Configuring ${NETWORK} for VPN"
		export CISCO_SPLIT_INC_${i}_ADDR=`echo $NETWORK | cut -d '/' -f 1`
		export CISCO_SPLIT_INC_${i}_MASK=`echo $NETWORK | cut -d '/' -f 2`
		export CISCO_SPLIT_INC_${i}_MASKLEN=`echo -p $NETWORK | cut -d '/' -f 3`
		i=`expr $i + 1`
	done
	export CISCO_SPLIT_INC=$i
	echo "We have ${CISCO_SPLIT_INC} networks"
	if [ -n "$CISCO_DEF_DOMAIN" ] ; then
		export CISCO_DEF_DOMAIN="$CISCO_DEF_DOMAIN cm.sourcefire.com englab.sourcefire.com sfeng.sourcefire.com denofslack.org"
	fi
fi 
echo "Saving existing resolv.conf to /etc/resolv.conf.SAVE_VPN"
cp -vf /etc/resolv.conf /etc/resolv.conf.SAVE_VPN